services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongodb:/home/mongodblocal/data"
    working_dir: /home/mongodblocal