services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongodb:/home/mongodblocal/data"
    working_dir: /home/mongodblocal
  redis:
    container_name: redis_local_db
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master